## Scientific computing tools

### The python stack

<img src='images/python_stack.png' width='600'>
Source: T. Connolly

Packages are collections of python code
Numpy - Numerical computing
SciPy - Stats, timeseries 
Matplotlib - Plotting and figure making
Other Packages:
   * Pandas: Data analysis
   * Basemap: Map making, working with geodata
   * xarray: 3D+ data

### The shell (bash)

[Bash methods](https://ss64.com/bash/) - Note: Not all will work in Git-Bash

Common commands:

* `ls` - list files and directories from current 
* `cd` - change directory
* `pwd` - list the present working directory
* `cp` - copy a file to another locations, for example 
```
cp data.txt documents
``` 
would copy a file called `data.txt` in the current directory to a sub-directory called `documents`.
* `mkdir` - make a new directory
* `..` - the parent directory

Python can be executed from the command line by typing `python` or `ipython`. Both if these commands open an interactive command line interface where Python commands can be entered and the output returned immediately. The IPython console provides a command line interface to Python that is designed to be as user-friendly as possible.

# Boolean logic

In the 19th century, in a book called _The Laws of Thought_, an Irish mathematician named George Boole developed a formal system of logic that laid the foundation for conveying information electronically. Boolean variables are a special type of variable that has two possible values: `True` or `False`. These binary values can also be represented as `1` or `0`. 

In [24]:
a = True
type(a)

bool

In Python, a double equals sign (`==`) tests for equivalancy. This is much different from the single equals sign (`=`), which is used for assignment (assigning a value to a variable).

In [25]:
print(1==1)
print(1==2)

True
False


In [26]:
# 1 and 0 can also represent True or False
print(1==True)
print(1==False)

True
False


In [27]:
# test for non-equivaalence
print(1 != 3)
print(1 >= 3) 

True
False


In [28]:
print(0 == 1)

False


In [29]:
print(0 == False)

True


In [30]:
print(True == (0 == 3))

False


In [31]:
print((False == (1==True)) != False)

False


In [32]:
#False = False

### Logic gates

In electronics, logic gates take multiple binary values (on/off) as input and produce a single binary value as output. These logic gates follow the laws of Boolean algebra. The same types of logic gates are used in computer programing. One type of logic gate is the __AND__ gate. The AND gate produces a `True` value only if both inputs are `True`.

A Logic Gate performs a logical operation on a binary inputs a single binary outputs

<img src='https://i.imgur.com/vbZhU10.jpg' >

source(https://imgur.com/vbZhU10)

In [33]:
print(0 and 0)
print(0 and 1)
print(1 and 0)
print(1 and 1)

0
0
0
1


The __OR__ gate produces a `True` value if at least one input is `True''.

In [34]:
print(0 or 0)
print(0 or 1)
print(1 or 0)
print(1 or 1)

0
1
1
1


## Conditional execution 

_If_ statements are used to execute a set of commands only under certain conditions. The syntax is shown below. Note that the commands to be run conditionally are indented with a tab.

<img src='https://www.programtopia.net/sites/default/files/if_0.png'>
source(https://www.programtopia.net/sites/default/files/if_0.png)

In [35]:
x = 1
if x > 0:
    print('x is positive')
    print('another line')
if not x > 0:
    print('x is negative')
print('done')

x is positive
another line
done


A chain of conditions can be created with `if`, `elif` and `else` blocks.
<img src='https://www.programtopia.net/sites/default/files/if..elseif_0.png'>
source( https://www.programtopia.net/sites/default/files/if..elseif_0.png)

In [36]:
if x > 0:
    print('x is positive')
elif x < 0:
    print('x is negative')
else:
    print('x is zero')

x is positive


__Exercise:__

Using conditional execution, calculate the absolute value of a number (not using the built-in `abs` function).

## Functions

Functions can be used to package a set of instructions. These instructions can then be reused for different inputs. Using functions can save you a lot of copying and pasting. Also, if you find a bug in your set of instructions, you only have to fix it once if you use a function instead of copying and pasting.

In [37]:
def mean(y):
    '''This function returns the mean of y'''
    meany = sum(y)/len(y)
    return meany

m = mean([1,2,3])
print(m)

2.0


In [38]:
help(mean)

Help on function mean in module __main__:

mean(y)
    This function returns the mean of y



In IPython (and Jupyter notebooks) there is another way of asking for help by typing the function name with a question mark.

`mean?`


__Exercises:__
    
* Create a function that takes a number as input, and returns the square of that number.
* Create a function to calculate the standard deviation of an array (not using the `np.sqrt` function).

## Loops

Loops are a way of repeating commands over and over again.

A _while_ loop is an indefinite loop. It runs indefinitely until a certain condition is met. Be careful with while loops. If the condition is never met, the while loop will try to run forever.

In [39]:
i = 0
while i<5:
    i = i + 1
    print(i)
print('done with while loop')

1
2
3
4
5
done with while loop


A _for_ loop is a definite loop. It iterates over a list, array or other variable types that are groups of values or other variables. It definitely stops when it gets to the end of the list.

In [40]:
name_list = ['Bob','Jane','Mary']
for name in name_list:
    print("Hello " + name)
print('done')         

Hello Bob
Hello Jane
Hello Mary
done


An example of looping through a sequence of numbers created with the `np.arange()` function.

In [41]:
import numpy as np
print(np.arange(5))

[0 1 2 3 4]


In [42]:
print(np.arange(2,5))

[2 3 4]


In [43]:
print(np.arange(2,5,0.5))

[ 2.   2.5  3.   3.5  4.   4.5]


In [44]:
for i in np.arange(5):
    print(i*2)

0
2
4
6
8


__Exercise__:

Write a for loop that prints out the cumulative sum of an array. For example, the cumulative sum of the array

```
[1,3,6,4,7]
```

would be:

```
[1,4,10,14,21]
```